# Site settings
title: Nel senso di sto blog!
email: sensorario@gmail.com
description: do your best and then deal with the conseguences
twitter_username: sensorario
github_username:  sensorario

# Build settings
markdown: kramdown
permalink: pretty
